apiVersion: batch/v1
kind: Job
metadata:
  name: model-prewarm
spec:
  template:
    spec:
      restartPolicy: Never

      containers:
        - name: prewarm
          image: curlimages/curl
          command:
            - sh
            - -c
            - |
              curl http://vllm:8000/v1/models
